[package]
name = "cof"
version = "0.1.0"
edition = "2021"
authors = ["Quinn Baker <quinn@quinnb.ca>"]

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }


[dependencies]
num = "0.2"
rand = "0.8.5"

[[bench]]
name = "cof_benchmark"
harness = false