[package]
name = "cof_tree"
version = "0.1.0"
edition = "2021"
authors = ["Quinn Baker <quinn@quinnb.ca>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cof = {path = "../cof"}
num = "0.2"